{% set namespace = "python" %}
{% set name = "cufflinks" %}
{% set version = "0.14.6" %}

package:
  name: {{ namespace|lower }}-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4188324361cc584214150aadaeb28ed07e9d150adb714b53c5f09d5b3fcdd28a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colorlover >=0.2.1
    - ipython >=5.3.0
    - ipywidgets >=7.0.0
    - numpy >=1.9.2
    - pandas >=0.19.2
    - plotly >=3.0.0
    - six >=1.9.0

test:
  imports:
    - cufflinks

about:
  home: https://github.com/santosjorge/cufflinks
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: 'Productivity Tools for Plotly + Pandas'

extra:
  recipe-maintainers:
    - dhirschfeld
